#Each new term in the Fibonacci sequence is generated by adding the 
#previous two terms.  By starting with 1 and 2, the first 10 terms
#will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

#By considering the terms in the Fibonacci sequence whose values do
#not exceed four million, find the sum of the even-valued terms.
terms = [1]
term = 1
previous = 1
sum = 2
begin
  terms << sum
  previous = term
  term = sum
  sum = term + previous 
end while sum < 4000000
#puts terms
puts terms.select{ |i| i.even? }.inject(0, :+)
